### ISSUE TITLE
Chose an alternative Electric slip ring

### ISSUE THREAD

**Issue by josepmaria-carbonell** [Integrated-Project-2-UVic-UCC/eyeSphere#3]
It is not possible to buy the Electric slip ring in the link supplied. 
Please check if one of the alternatives are suitable for you. 

1.  https://www.amazon.es/WayinTop-deslizante-el%C3%A9ctrico-alambres-CIRCUITOS/dp/B07GCNK2XY
2.  https://www.amazon.es/BQLZR-500-rpm-hattype-antideslizante-electr%C3%B3nicos/dp/B01CJJNL46

We will expect your answer before to order it.

@Integrated-Project-2-UVic-UCC/eye-sphere

**Comment by SergiMuac** [comment]
Hi,
I've been checking the links you send us, and unfortunately, they doesn't fit in our project.
I found another link that could be a good option:

https://www.amazon.es/dp/B085MFQC7X/ref=cm_sw_r_cp_apa_i_QTGR91SPD405WSQCWYE8

If is not possible to buy the product in the link above, feel free to chose another model but only if it has the following specifications:
- 4 wires
- minimum 2A
- recomended max speed 300rpm, but if it's less, we will adapt to it.

Thanks,
EyeSphere team.

@josepmaria-carbonell @moises-garin

**Comment by josepmaria-carbonell** [comment]
Good, the ring arrived.  Finally we got this one.

https://www.amazon.es/WayinTop-deslizante-el%C3%A9ctrico-alambres-CIRCUITOS/dp/B07GCNK2XY

If data is not transmitted correctly, a Bluetooth communication is going to be used and added to the system.
